//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Local, within-document reference.
 * 
 * <p>Java class for AbstractLocalRef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractLocalRef">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://rs.tdwg.org/UBIF/2006/}AbstractRef">
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractLocalRef")
@XmlSeeAlso({
    ConceptStateRef.class,
    CharTreeNodeRef.class,
    StoredKeyRef.class,
    SamplingEventRef.class,
    TaxonHierarchyRef.class,
    SpecimenRef.class,
    ModifierRefWithData.class,
    MediaObjectRef.class,
    GeographicAreaRef.class,
    TaxonHierarchyNodeRef.class,
    TaxonNameRef.class,
    CharacterRef.class,
    MediaObjectRichRef.class,
    DescriptiveConceptRef.class,
    AgentRef.class,
    CharacterStateRef.class,
    PublicationRef.class,
    StoredKeyNodeRef.class
})
public class AbstractLocalRef
    extends AbstractRef
{


}
