//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base of modifiers, stat. meas. elaborations, and categorical character states (both referrable concept and local character state definitions).
 * 
 * Any use of a modifier or character state in descriptions is a reference to an object derived from this class.
 * 
 * <p>Java class for AbstractVocabularyBase complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractVocabularyBase">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractObject">
 *       &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}NaturalLanguageGroup" minOccurs="0"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractVocabularyBase", propOrder = {
    "naturalLanguage"
})
@XmlSeeAlso({
    CharacterLocalStateDef.class,
    ConceptStateDef.class,
    UnivarStatMeasureElaboration.class,
    ModifierDef.class
})
public abstract class AbstractVocabularyBase
    extends AbstractObject
{

    @XmlElement(name = "NaturalLanguage")
    protected NaturalLanguagePhraseSet naturalLanguage;

    /**
     * Gets the value of the naturalLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link NaturalLanguagePhraseSet }
     *     
     */
    public NaturalLanguagePhraseSet getNaturalLanguage() {
        return naturalLanguage;
    }

    /**
     * Sets the value of the naturalLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link NaturalLanguagePhraseSet }
     *     
     */
    public void setNaturalLanguage(NaturalLanguagePhraseSet value) {
        this.naturalLanguage = value;
    }

}
