//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A name string expressing the agent as a literal, optionally enriched (email, address), optionally plus references pointing to Agent objects (local ref or uri), used for authors, editors, collectors, etc., whenever the identity of an Agent often cannot be associated with an Agent without doubt (example: 2 authors J. Smith may be different persons, but 'J. Smith' and 'J. M. Smith' may be the same person)
 * 
 * <p>Java class for AgentString complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AgentString">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractShortStringPlusRef">
 *       &lt;attribute name="email" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" />
 *       &lt;attribute name="phone" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" />
 *       &lt;attribute name="address" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AgentString")
public class AgentString
    extends AbstractShortStringPlusRef
{

    @XmlAttribute(name = "email")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String email;
    @XmlAttribute(name = "phone")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String phone;
    @XmlAttribute(name = "address")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String address;

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

}
