//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * # Derived from AbstractCharSummaryData to be used for categorical (char. state) data in instance documents (non-abstract type) 
 * 
 * <p>Java class for CatSummaryData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CatSummaryData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractCharSummaryData">
 *       &lt;sequence>
 *         &lt;element name="State" type="{http://rs.tdwg.org/UBIF/2006/}StateData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="statemodel" type="{http://rs.tdwg.org/UBIF/2006/}StateCollectionModelEnum" default="OrSet" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CatSummaryData", propOrder = {
    "state",
    "nextVersion"
})
public class CatSummaryData
    extends AbstractCharSummaryData
{

    @XmlElement(name = "State")
    protected List<StateData> state;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;
    @XmlAttribute(name = "statemodel")
    protected QName statemodel;

    /**
     * Gets the value of the state property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the state property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateData }
     * 
     * 
     */
    public List<StateData> getState() {
        if (state == null) {
            state = new ArrayList<StateData>();
        }
        return this.state;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

    /**
     * Gets the value of the statemodel property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getStatemodel() {
        if (statemodel == null) {
            return new QName("http://rs.tdwg.org/UBIF/2006/", "OrSet", "");
        } else {
            return statemodel;
        }
    }

    /**
     * Sets the value of the statemodel property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setStatemodel(QName value) {
        this.statemodel = value;
    }

}
