//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines an entire character tree
 * (which may be a tree or a single tree node containing a flat list)
 * 
 * <p>Java class for CharacterTree complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterTree">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}VersionedAbstractObject">
 *       &lt;sequence>
 *         &lt;element name="Scope" type="{http://rs.tdwg.org/UBIF/2006/}TaxonomicScopeSet" minOccurs="0"/>
 *         &lt;element name="DesignedFor" type="{http://rs.tdwg.org/UBIF/2006/}CharTree_DesignedForSet" minOccurs="0"/>
 *         &lt;element name="ShouldContainAllCharacters" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Nodes" type="{http://rs.tdwg.org/UBIF/2006/}CharTree_NodeSeq"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterTree", propOrder = {
    "scope",
    "designedFor",
    "shouldContainAllCharacters",
    "nodes",
    "nextVersion"
})
public class CharacterTree
    extends VersionedAbstractObject
{

    @XmlElement(name = "Scope")
    protected TaxonomicScopeSet scope;
    @XmlElement(name = "DesignedFor")
    protected CharTreeDesignedForSet designedFor;
    @XmlElement(name = "ShouldContainAllCharacters", defaultValue = "false")
    protected Boolean shouldContainAllCharacters;
    @XmlElement(name = "Nodes", required = true)
    protected CharTreeNodeSeq nodes;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonomicScopeSet }
     *     
     */
    public TaxonomicScopeSet getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonomicScopeSet }
     *     
     */
    public void setScope(TaxonomicScopeSet value) {
        this.scope = value;
    }

    /**
     * Gets the value of the designedFor property.
     * 
     * @return
     *     possible object is
     *     {@link CharTreeDesignedForSet }
     *     
     */
    public CharTreeDesignedForSet getDesignedFor() {
        return designedFor;
    }

    /**
     * Sets the value of the designedFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharTreeDesignedForSet }
     *     
     */
    public void setDesignedFor(CharTreeDesignedForSet value) {
        this.designedFor = value;
    }

    /**
     * Gets the value of the shouldContainAllCharacters property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShouldContainAllCharacters() {
        return shouldContainAllCharacters;
    }

    /**
     * Sets the value of the shouldContainAllCharacters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShouldContainAllCharacters(Boolean value) {
        this.shouldContainAllCharacters = value;
    }

    /**
     * Gets the value of the nodes property.
     * 
     * @return
     *     possible object is
     *     {@link CharTreeNodeSeq }
     *     
     */
    public CharTreeNodeSeq getNodes() {
        return nodes;
    }

    /**
     * Sets the value of the nodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CharTreeNodeSeq }
     *     
     */
    public void setNodes(CharTreeNodeSeq value) {
        this.nodes = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
