//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CharacterSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CharacterSet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}Set">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="CategoricalCharacter" type="{http://rs.tdwg.org/UBIF/2006/}CategoricalCharacter"/>
 *         &lt;element name="QuantitativeCharacter" type="{http://rs.tdwg.org/UBIF/2006/}QuantitativeCharacter"/>
 *         &lt;element name="TextCharacter" type="{http://rs.tdwg.org/UBIF/2006/}TextCharacter"/>
 *         &lt;element name="SequenceCharacter" type="{http://rs.tdwg.org/UBIF/2006/}MolecularSequenceCharacter"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CharacterSet", propOrder = {
    "categoricalCharacterOrQuantitativeCharacterOrTextCharacter"
})
public class CharacterSet
    extends Set
{

    @XmlElements({
        @XmlElement(name = "SequenceCharacter", type = MolecularSequenceCharacter.class),
        @XmlElement(name = "TextCharacter", type = TextCharacter.class),
        @XmlElement(name = "QuantitativeCharacter", type = QuantitativeCharacter.class),
        @XmlElement(name = "CategoricalCharacter", type = CategoricalCharacter.class)
    })
    protected List<AbstractCharacterDefinition> categoricalCharacterOrQuantitativeCharacterOrTextCharacter;

    /**
     * Gets the value of the categoricalCharacterOrQuantitativeCharacterOrTextCharacter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoricalCharacterOrQuantitativeCharacterOrTextCharacter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoricalCharacterOrQuantitativeCharacterOrTextCharacter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MolecularSequenceCharacter }
     * {@link TextCharacter }
     * {@link QuantitativeCharacter }
     * {@link CategoricalCharacter }
     * 
     * 
     */
    public List<AbstractCharacterDefinition> getCategoricalCharacterOrQuantitativeCharacterOrTextCharacter() {
        if (categoricalCharacterOrQuantitativeCharacterOrTextCharacter == null) {
            categoricalCharacterOrQuantitativeCharacterOrTextCharacter = new ArrayList<AbstractCharacterDefinition>();
        }
        return this.categoricalCharacterOrQuantitativeCharacterOrTextCharacter;
    }

}
