//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * DescriptiveConcepts may be basic
 * properties (color, shape,
 * texture), structural types
 * (fruit types), methods
 * (naked eye, hand lens,
 * microscope) or other
 * hierarchical generalizations that can be applied to characters
 * (e. g., relative region: tip
 * versus base of structure)
 * 
 * Note that a number of ontological relations between concepts may be expressed using the general link structure of the base type (subclass, part of, etc.).
 * 
 * <p>Java class for DescriptiveConcept complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptiveConcept">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}VersionedAbstractObject">
 *       &lt;sequence>
 *         &lt;element name="Modifiers" type="{http://rs.tdwg.org/UBIF/2006/}ModifierSeq" minOccurs="0"/>
 *         &lt;element name="ConceptStates" type="{http://rs.tdwg.org/UBIF/2006/}ConceptStateSeq" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptiveConcept", propOrder = {
    "modifiers",
    "conceptStates",
    "nextVersion"
})
public class DescriptiveConcept
    extends VersionedAbstractObject
{

    @XmlElement(name = "Modifiers")
    protected ModifierSeq modifiers;
    @XmlElement(name = "ConceptStates")
    protected ConceptStateSeq conceptStates;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the modifiers property.
     * 
     * @return
     *     possible object is
     *     {@link ModifierSeq }
     *     
     */
    public ModifierSeq getModifiers() {
        return modifiers;
    }

    /**
     * Sets the value of the modifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifierSeq }
     *     
     */
    public void setModifiers(ModifierSeq value) {
        this.modifiers = value;
    }

    /**
     * Gets the value of the conceptStates property.
     * 
     * @return
     *     possible object is
     *     {@link ConceptStateSeq }
     *     
     */
    public ConceptStateSeq getConceptStates() {
        return conceptStates;
    }

    /**
     * Sets the value of the conceptStates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConceptStateSeq }
     *     
     */
    public void setConceptStates(ConceptStateSeq value) {
        this.conceptStates = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
