//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Canonical name of a taxon (normalized according to nomenclatural code rules, without non-required hierarchy elements like subgenus for a species, or more than one infraspecific epithet ('G. spex var. x  f. y').
 * 
 * <p>Java class for LinneanCanonicalTaxonName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinneanCanonicalTaxonName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Simple" type="{http://rs.tdwg.org/UBIF/2006/}ShortString"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="SupragenericName" type="{http://rs.tdwg.org/UBIF/2006/}ShortString"/>
 *           &lt;sequence>
 *             &lt;element name="Genus" type="{http://rs.tdwg.org/UBIF/2006/}TaxonString"/>
 *             &lt;choice minOccurs="0">
 *               &lt;element name="InfragenericEpithet" type="{http://rs.tdwg.org/UBIF/2006/}ShortString"/>
 *               &lt;sequence>
 *                 &lt;element name="SpecificEpithet" type="{http://rs.tdwg.org/UBIF/2006/}TaxonString"/>
 *                 &lt;element name="InfraspecificEpithet" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" minOccurs="0"/>
 *                 &lt;element name="CultivarNameGroup" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" minOccurs="0"/>
 *               &lt;/sequence>
 *             &lt;/choice>
 *           &lt;/sequence>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinneanCanonicalTaxonName", propOrder = {
    "simple",
    "supragenericName",
    "genus",
    "infragenericEpithet",
    "specificEpithet",
    "infraspecificEpithet",
    "cultivarNameGroup"
})
public class LinneanCanonicalTaxonName {

    @XmlElement(name = "Simple", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String simple;
    @XmlElement(name = "SupragenericName")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String supragenericName;
    @XmlElement(name = "Genus")
    protected TaxonString genus;
    @XmlElement(name = "InfragenericEpithet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String infragenericEpithet;
    @XmlElement(name = "SpecificEpithet")
    protected TaxonString specificEpithet;
    @XmlElement(name = "InfraspecificEpithet")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String infraspecificEpithet;
    @XmlElement(name = "CultivarNameGroup")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String cultivarNameGroup;

    /**
     * Gets the value of the simple property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimple() {
        return simple;
    }

    /**
     * Sets the value of the simple property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimple(String value) {
        this.simple = value;
    }

    /**
     * Gets the value of the supragenericName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupragenericName() {
        return supragenericName;
    }

    /**
     * Sets the value of the supragenericName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupragenericName(String value) {
        this.supragenericName = value;
    }

    /**
     * Gets the value of the genus property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonString }
     *     
     */
    public TaxonString getGenus() {
        return genus;
    }

    /**
     * Sets the value of the genus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonString }
     *     
     */
    public void setGenus(TaxonString value) {
        this.genus = value;
    }

    /**
     * Gets the value of the infragenericEpithet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfragenericEpithet() {
        return infragenericEpithet;
    }

    /**
     * Sets the value of the infragenericEpithet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfragenericEpithet(String value) {
        this.infragenericEpithet = value;
    }

    /**
     * Gets the value of the specificEpithet property.
     * 
     * @return
     *     possible object is
     *     {@link TaxonString }
     *     
     */
    public TaxonString getSpecificEpithet() {
        return specificEpithet;
    }

    /**
     * Sets the value of the specificEpithet property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaxonString }
     *     
     */
    public void setSpecificEpithet(TaxonString value) {
        this.specificEpithet = value;
    }

    /**
     * Gets the value of the infraspecificEpithet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInfraspecificEpithet() {
        return infraspecificEpithet;
    }

    /**
     * Sets the value of the infraspecificEpithet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInfraspecificEpithet(String value) {
        this.infraspecificEpithet = value;
    }

    /**
     * Gets the value of the cultivarNameGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCultivarNameGroup() {
        return cultivarNameGroup;
    }

    /**
     * Sets the value of the cultivarNameGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCultivarNameGroup(String value) {
        this.cultivarNameGroup = value;
    }

}
