//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Formatted text with some additional optional attributes, used for Text and Note elements inside the NaturalLanguageDescription container.
 * 
 * <p>Java class for MarkupText complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarkupText">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://rs.tdwg.org/UBIF/2006/>LongStringL">
 *       &lt;attribute name="parsed" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="newparagraph" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="pagenumber" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" />
 *       &lt;anyAttribute namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarkupText")
public class MarkupText
    extends LongStringL
{

    @XmlAttribute(name = "parsed")
    protected Boolean parsed;
    @XmlAttribute(name = "newparagraph")
    protected Boolean newparagraph;
    @XmlAttribute(name = "pagenumber")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String pagenumber;

    /**
     * Gets the value of the parsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isParsed() {
        if (parsed == null) {
            return false;
        } else {
            return parsed;
        }
    }

    /**
     * Sets the value of the parsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setParsed(Boolean value) {
        this.parsed = value;
    }

    /**
     * Gets the value of the newparagraph property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isNewparagraph() {
        if (newparagraph == null) {
            return false;
        } else {
            return newparagraph;
        }
    }

    /**
     * Sets the value of the newparagraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNewparagraph(Boolean value) {
        this.newparagraph = value;
    }

    /**
     * Gets the value of the pagenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPagenumber() {
        return pagenumber;
    }

    /**
     * Sets the value of the pagenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPagenumber(String value) {
        this.pagenumber = value;
    }

}
