//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * State or character modifier definitions (certainty, frequency, spatial, temporal, etc.)
 * 
 * <p>Java class for ModifierDef complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModifierDef">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractVocabularyBase">
 *       &lt;sequence>
 *         &lt;element name="ModifierClass" type="{http://rs.tdwg.org/UBIF/2006/}ModifierClassEnum" minOccurs="0"/>
 *         &lt;element name="ProportionRange" type="{http://rs.tdwg.org/UBIF/2006/}ZeroToOneEstimateRange" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModifierDef", propOrder = {
    "modifierClass",
    "proportionRange",
    "nextVersion"
})
public class ModifierDef
    extends AbstractVocabularyBase
{

    @XmlElement(name = "ModifierClass", defaultValue = "OtherModifierClass")
    protected QName modifierClass;
    @XmlElement(name = "ProportionRange")
    protected ZeroToOneEstimateRange proportionRange;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the modifierClass property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getModifierClass() {
        return modifierClass;
    }

    /**
     * Sets the value of the modifierClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setModifierClass(QName value) {
        this.modifierClass = value;
    }

    /**
     * Gets the value of the proportionRange property.
     * 
     * @return
     *     possible object is
     *     {@link ZeroToOneEstimateRange }
     *     
     */
    public ZeroToOneEstimateRange getProportionRange() {
        return proportionRange;
    }

    /**
     * Sets the value of the proportionRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZeroToOneEstimateRange }
     *     
     */
    public void setProportionRange(ZeroToOneEstimateRange value) {
        this.proportionRange = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
