//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.tdwg.rs.ubif._2006 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QuantitativeMarkupText_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Text");
    private final static QName _QuantitativeMarkupStatus_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Status");
    private final static QName _QuantitativeMarkupValue_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Value");
    private final static QName _QuantitativeMarkupMeasure_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Measure");
    private final static QName _QuantitativeMarkupPMeasure_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "PMeasure");
    private final static QName _QuantitativeMarkupNote_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Note");
    private final static QName _QuantitativeMarkupModifier_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Modifier");
    private final static QName _CategoricalMarkupState_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "State");
    private final static QName _SamplingUnitDataSetTextChar_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "TextChar");
    private final static QName _SamplingUnitDataSetQuantitative_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Quantitative");
    private final static QName _SamplingUnitDataSetSequence_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Sequence");
    private final static QName _SamplingUnitDataSetCategorical_QNAME = new QName("http://rs.tdwg.org/UBIF/2006/", "Categorical");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.tdwg.rs.ubif._2006
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaxonNameCore }
     * 
     */
    public TaxonNameCore createTaxonNameCore() {
        return new TaxonNameCore();
    }

    /**
     * Create an instance of {@link ConceptStateSeq }
     * 
     */
    public ConceptStateSeq createConceptStateSeq() {
        return new ConceptStateSeq();
    }

    /**
     * Create an instance of {@link QuantitativeCharacter }
     * 
     */
    public QuantitativeCharacter createQuantitativeCharacter() {
        return new QuantitativeCharacter();
    }

    /**
     * Create an instance of {@link SamplingEventRef }
     * 
     */
    public SamplingEventRef createSamplingEventRef() {
        return new SamplingEventRef();
    }

    /**
     * Create an instance of {@link CharTreeNode }
     * 
     */
    public CharTreeNode createCharTreeNode() {
        return new CharTreeNode();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link LongStringL }
     * 
     */
    public LongStringL createLongStringL() {
        return new LongStringL();
    }

    /**
     * Create an instance of {@link MediaObjectSet }
     * 
     */
    public MediaObjectSet createMediaObjectSet() {
        return new MediaObjectSet();
    }

    /**
     * Create an instance of {@link CategoricalCharMapping }
     * 
     */
    public CategoricalCharMapping createCategoricalCharMapping() {
        return new CategoricalCharMapping();
    }

    /**
     * Create an instance of {@link ModifierDef }
     * 
     */
    public ModifierDef createModifierDef() {
        return new ModifierDef();
    }

    /**
     * Create an instance of {@link CatSampleData }
     * 
     */
    public CatSampleData createCatSampleData() {
        return new CatSampleData();
    }

    /**
     * Create an instance of {@link AbstractLocalRef }
     * 
     */
    public AbstractLocalRef createAbstractLocalRef() {
        return new AbstractLocalRef();
    }

    /**
     * Create an instance of {@link QuantitativeCharMapping }
     * 
     */
    public QuantitativeCharMapping createQuantitativeCharMapping() {
        return new QuantitativeCharMapping();
    }

    /**
     * Create an instance of {@link OwnerRefSeq }
     * 
     */
    public OwnerRefSeq createOwnerRefSeq() {
        return new OwnerRefSeq();
    }

    /**
     * Create an instance of {@link ConceptMarkup }
     * 
     */
    public ConceptMarkup createConceptMarkup() {
        return new ConceptMarkup();
    }

    /**
     * Create an instance of {@link CompositeDateTime }
     * 
     */
    public CompositeDateTime createCompositeDateTime() {
        return new CompositeDateTime();
    }

    /**
     * Create an instance of {@link TaxonomicScopeSet }
     * 
     */
    public TaxonomicScopeSet createTaxonomicScopeSet() {
        return new TaxonomicScopeSet();
    }

    /**
     * Create an instance of {@link TechnicalMetadata }
     * 
     */
    public TechnicalMetadata createTechnicalMetadata() {
        return new TechnicalMetadata();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link StoredKeyNode.Question }
     * 
     */
    public StoredKeyNode.Question createStoredKeyNodeQuestion() {
        return new StoredKeyNode.Question();
    }

    /**
     * Create an instance of {@link DependencyRules }
     * 
     */
    public DependencyRules createDependencyRules() {
        return new DependencyRules();
    }

    /**
     * Create an instance of {@link IdentificationKeySet }
     * 
     */
    public IdentificationKeySet createIdentificationKeySet() {
        return new IdentificationKeySet();
    }

    /**
     * Create an instance of {@link DataStatusData }
     * 
     */
    public DataStatusData createDataStatusData() {
        return new DataStatusData();
    }

    /**
     * Create an instance of {@link TaxonNameRefSeq }
     * 
     */
    public TaxonNameRefSeq createTaxonNameRefSeq() {
        return new TaxonNameRefSeq();
    }

    /**
     * Create an instance of {@link StateData }
     * 
     */
    public StateData createStateData() {
        return new StateData();
    }

    /**
     * Create an instance of {@link MolecularSequenceCharacter }
     * 
     */
    public MolecularSequenceCharacter createMolecularSequenceCharacter() {
        return new MolecularSequenceCharacter();
    }

    /**
     * Create an instance of {@link ConceptStateDef }
     * 
     */
    public ConceptStateDef createConceptStateDef() {
        return new ConceptStateDef();
    }

    /**
     * Create an instance of {@link NaturalLanguageDescriptionSet }
     * 
     */
    public NaturalLanguageDescriptionSet createNaturalLanguageDescriptionSet() {
        return new NaturalLanguageDescriptionSet();
    }

    /**
     * Create an instance of {@link TextCharacter }
     * 
     */
    public TextCharacter createTextCharacter() {
        return new TextCharacter();
    }

    /**
     * Create an instance of {@link RatingSet }
     * 
     */
    public RatingSet createRatingSet() {
        return new RatingSet();
    }

    /**
     * Create an instance of {@link ShortStringL }
     * 
     */
    public ShortStringL createShortStringL() {
        return new ShortStringL();
    }

    /**
     * Create an instance of {@link CategoricalMarkup }
     * 
     */
    public CategoricalMarkup createCategoricalMarkup() {
        return new CategoricalMarkup();
    }

    /**
     * Create an instance of {@link AbstractLongStringPlusRef }
     * 
     */
    public AbstractLongStringPlusRef createAbstractLongStringPlusRef() {
        return new AbstractLongStringPlusRef();
    }

    /**
     * Create an instance of {@link MeasureMarkup }
     * 
     */
    public MeasureMarkup createMeasureMarkup() {
        return new MeasureMarkup();
    }

    /**
     * Create an instance of {@link CharacterSet }
     * 
     */
    public CharacterSet createCharacterSet() {
        return new CharacterSet();
    }

    /**
     * Create an instance of {@link CompositeDate }
     * 
     */
    public CompositeDate createCompositeDate() {
        return new CompositeDate();
    }

    /**
     * Create an instance of {@link SimpleRepresentation }
     * 
     */
    public SimpleRepresentation createSimpleRepresentation() {
        return new SimpleRepresentation();
    }

    /**
     * Create an instance of {@link GeographicAreaSet }
     * 
     */
    public GeographicAreaSet createGeographicAreaSet() {
        return new GeographicAreaSet();
    }

    /**
     * Create an instance of {@link ValueRangeWithClass }
     * 
     */
    public ValueRangeWithClass createValueRangeWithClass() {
        return new ValueRangeWithClass();
    }

    /**
     * Create an instance of {@link TaxonHierarchyRef }
     * 
     */
    public TaxonHierarchyRef createTaxonHierarchyRef() {
        return new TaxonHierarchyRef();
    }

    /**
     * Create an instance of {@link AgentStringSeq }
     * 
     */
    public AgentStringSeq createAgentStringSeq() {
        return new AgentStringSeq();
    }

    /**
     * Create an instance of {@link CharTreeNodeSeq }
     * 
     */
    public CharTreeNodeSeq createCharTreeNodeSeq() {
        return new CharTreeNodeSeq();
    }

    /**
     * Create an instance of {@link SummaryDataSet }
     * 
     */
    public SummaryDataSet createSummaryDataSet() {
        return new SummaryDataSet();
    }

    /**
     * Create an instance of {@link TaxonNameSet }
     * 
     */
    public TaxonNameSet createTaxonNameSet() {
        return new TaxonNameSet();
    }

    /**
     * Create an instance of {@link LinkSet }
     * 
     */
    public LinkSet createLinkSet() {
        return new LinkSet();
    }

    /**
     * Create an instance of {@link AgentString }
     * 
     */
    public AgentString createAgentString() {
        return new AgentString();
    }

    /**
     * Create an instance of {@link StoredKeyRef }
     * 
     */
    public StoredKeyRef createStoredKeyRef() {
        return new StoredKeyRef();
    }

    /**
     * Create an instance of {@link StoredKey }
     * 
     */
    public StoredKey createStoredKey() {
        return new StoredKey();
    }

    /**
     * Create an instance of {@link PMeasureMarkup }
     * 
     */
    public PMeasureMarkup createPMeasureMarkup() {
        return new PMeasureMarkup();
    }

    /**
     * Create an instance of {@link ContributorRef }
     * 
     */
    public ContributorRef createContributorRef() {
        return new ContributorRef();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link UnivarSimpleStatMeasureData }
     * 
     */
    public UnivarSimpleStatMeasureData createUnivarSimpleStatMeasureData() {
        return new UnivarSimpleStatMeasureData();
    }

    /**
     * Create an instance of {@link Representation }
     * 
     */
    public Representation createRepresentation() {
        return new Representation();
    }

    /**
     * Create an instance of {@link CreatorRef }
     * 
     */
    public CreatorRef createCreatorRef() {
        return new CreatorRef();
    }

    /**
     * Create an instance of {@link CharacterRef }
     * 
     */
    public CharacterRef createCharacterRef() {
        return new CharacterRef();
    }

    /**
     * Create an instance of {@link Datasets }
     * 
     */
    public Datasets createDatasets() {
        return new Datasets();
    }

    /**
     * Create an instance of {@link DataStatusMarkup }
     * 
     */
    public DataStatusMarkup createDataStatusMarkup() {
        return new DataStatusMarkup();
    }

    /**
     * Create an instance of {@link TaxonAuthorshipCitation }
     * 
     */
    public TaxonAuthorshipCitation createTaxonAuthorshipCitation() {
        return new TaxonAuthorshipCitation();
    }

    /**
     * Create an instance of {@link StoredKey.Question }
     * 
     */
    public StoredKey.Question createStoredKeyQuestion() {
        return new StoredKey.Question();
    }

    /**
     * Create an instance of {@link AgentSet }
     * 
     */
    public AgentSet createAgentSet() {
        return new AgentSet();
    }

    /**
     * Create an instance of {@link GeographicArea }
     * 
     */
    public GeographicArea createGeographicArea() {
        return new GeographicArea();
    }

    /**
     * Create an instance of {@link CharacterStateRefSet }
     * 
     */
    public CharacterStateRefSet createCharacterStateRefSet() {
        return new CharacterStateRefSet();
    }

    /**
     * Create an instance of {@link DescriptiveConcept }
     * 
     */
    public DescriptiveConcept createDescriptiveConcept() {
        return new DescriptiveConcept();
    }

    /**
     * Create an instance of {@link CharTreeCharacter }
     * 
     */
    public CharTreeCharacter createCharTreeCharacter() {
        return new CharTreeCharacter();
    }

    /**
     * Create an instance of {@link GeographicalCoordinates }
     * 
     */
    public GeographicalCoordinates createGeographicalCoordinates() {
        return new GeographicalCoordinates();
    }

    /**
     * Create an instance of {@link CategoricalCharacter }
     * 
     */
    public CategoricalCharacter createCategoricalCharacter() {
        return new CategoricalCharacter();
    }

    /**
     * Create an instance of {@link MolecularSequenceData }
     * 
     */
    public MolecularSequenceData createMolecularSequenceData() {
        return new MolecularSequenceData();
    }

    /**
     * Create an instance of {@link NatLangPhraseString }
     * 
     */
    public NatLangPhraseString createNatLangPhraseString() {
        return new NatLangPhraseString();
    }

    /**
     * Create an instance of {@link TaxonString }
     * 
     */
    public TaxonString createTaxonString() {
        return new TaxonString();
    }

    /**
     * Create an instance of {@link Publication }
     * 
     */
    public Publication createPublication() {
        return new Publication();
    }

    /**
     * Create an instance of {@link AudienceSet }
     * 
     */
    public AudienceSet createAudienceSet() {
        return new AudienceSet();
    }

    /**
     * Create an instance of {@link DocumentGenerator }
     * 
     */
    public DocumentGenerator createDocumentGenerator() {
        return new DocumentGenerator();
    }

    /**
     * Create an instance of {@link FreeFormTextMarkup }
     * 
     */
    public FreeFormTextMarkup createFreeFormTextMarkup() {
        return new FreeFormTextMarkup();
    }

    /**
     * Create an instance of {@link Dataset }
     * 
     */
    public Dataset createDataset() {
        return new Dataset();
    }

    /**
     * Create an instance of {@link ZeroToOneRange }
     * 
     */
    public ZeroToOneRange createZeroToOneRange() {
        return new ZeroToOneRange();
    }

    /**
     * Create an instance of {@link AgentRef }
     * 
     */
    public AgentRef createAgentRef() {
        return new AgentRef();
    }

    /**
     * Create an instance of {@link CreatorContributorRef }
     * 
     */
    public CreatorContributorRef createCreatorContributorRef() {
        return new CreatorContributorRef();
    }

    /**
     * Create an instance of {@link RevisionData }
     * 
     */
    public RevisionData createRevisionData() {
        return new RevisionData();
    }

    /**
     * Create an instance of {@link QuantitativeCharacter.MeasurementUnit }
     * 
     */
    public QuantitativeCharacter.MeasurementUnit createQuantitativeCharacterMeasurementUnit() {
        return new QuantitativeCharacter.MeasurementUnit();
    }

    /**
     * Create an instance of {@link SpecimenCore }
     * 
     */
    public SpecimenCore createSpecimenCore() {
        return new SpecimenCore();
    }

    /**
     * Create an instance of {@link StoredKeyNode.CodedStatements }
     * 
     */
    public StoredKeyNode.CodedStatements createStoredKeyNodeCodedStatements() {
        return new StoredKeyNode.CodedStatements();
    }

    /**
     * Create an instance of {@link MarkupText }
     * 
     */
    public MarkupText createMarkupText() {
        return new MarkupText();
    }

    /**
     * Create an instance of {@link StoredKeyLeadSeq }
     * 
     */
    public StoredKeyLeadSeq createStoredKeyLeadSeq() {
        return new StoredKeyLeadSeq();
    }

    /**
     * Create an instance of {@link CategoricalCharAssumptions }
     * 
     */
    public CategoricalCharAssumptions createCategoricalCharAssumptions() {
        return new CategoricalCharAssumptions();
    }

    /**
     * Create an instance of {@link SamplingUnitDataSet }
     * 
     */
    public SamplingUnitDataSet createSamplingUnitDataSet() {
        return new SamplingUnitDataSet();
    }

    /**
     * Create an instance of {@link StoredKeyNodeRef }
     * 
     */
    public StoredKeyNodeRef createStoredKeyNodeRef() {
        return new StoredKeyNodeRef();
    }

    /**
     * Create an instance of {@link GeographicAreaRef }
     * 
     */
    public GeographicAreaRef createGeographicAreaRef() {
        return new GeographicAreaRef();
    }

    /**
     * Create an instance of {@link MediaObject }
     * 
     */
    public MediaObject createMediaObject() {
        return new MediaObject();
    }

    /**
     * Create an instance of {@link NaturalLanguageMarkup }
     * 
     */
    public NaturalLanguageMarkup createNaturalLanguageMarkup() {
        return new NaturalLanguageMarkup();
    }

    /**
     * Create an instance of {@link TaxonHierarchyCore }
     * 
     */
    public TaxonHierarchyCore createTaxonHierarchyCore() {
        return new TaxonHierarchyCore();
    }

    /**
     * Create an instance of {@link CitationString }
     * 
     */
    public CitationString createCitationString() {
        return new CitationString();
    }

    /**
     * Create an instance of {@link CodedDescription }
     * 
     */
    public CodedDescription createCodedDescription() {
        return new CodedDescription();
    }

    /**
     * Create an instance of {@link TaxonHierarchyNode }
     * 
     */
    public TaxonHierarchyNode createTaxonHierarchyNode() {
        return new TaxonHierarchyNode();
    }

    /**
     * Create an instance of {@link CreatorRefSeq }
     * 
     */
    public CreatorRefSeq createCreatorRefSeq() {
        return new CreatorRefSeq();
    }

    /**
     * Create an instance of {@link ExtendedScopeSet }
     * 
     */
    public ExtendedScopeSet createExtendedScopeSet() {
        return new ExtendedScopeSet();
    }

    /**
     * Create an instance of {@link RepresentationReqrd }
     * 
     */
    public RepresentationReqrd createRepresentationReqrd() {
        return new RepresentationReqrd();
    }

    /**
     * Create an instance of {@link URIRef }
     * 
     */
    public URIRef createURIRef() {
        return new URIRef();
    }

    /**
     * Create an instance of {@link LabelText }
     * 
     */
    public LabelText createLabelText() {
        return new LabelText();
    }

    /**
     * Create an instance of {@link OwnerRef }
     * 
     */
    public OwnerRef createOwnerRef() {
        return new OwnerRef();
    }

    /**
     * Create an instance of {@link QuantitativeCharAssumptions }
     * 
     */
    public QuantitativeCharAssumptions createQuantitativeCharAssumptions() {
        return new QuantitativeCharAssumptions();
    }

    /**
     * Create an instance of {@link QuantitativeMarkup }
     * 
     */
    public QuantitativeMarkup createQuantitativeMarkup() {
        return new QuantitativeMarkup();
    }

    /**
     * Create an instance of {@link Agent }
     * 
     */
    public Agent createAgent() {
        return new Agent();
    }

    /**
     * Create an instance of {@link IPRStatement }
     * 
     */
    public IPRStatement createIPRStatement() {
        return new IPRStatement();
    }

    /**
     * Create an instance of {@link TaxonHierarchyNodeRef }
     * 
     */
    public TaxonHierarchyNodeRef createTaxonHierarchyNodeRef() {
        return new TaxonHierarchyNodeRef();
    }

    /**
     * Create an instance of {@link DataStatus }
     * 
     */
    public DataStatus createDataStatus() {
        return new DataStatus();
    }

    /**
     * Create an instance of {@link CharTreeNodeRef }
     * 
     */
    public CharTreeNodeRef createCharTreeNodeRef() {
        return new CharTreeNodeRef();
    }

    /**
     * Create an instance of {@link CharTreeAbstractNode }
     * 
     */
    public CharTreeAbstractNode createCharTreeAbstractNode() {
        return new CharTreeAbstractNode();
    }

    /**
     * Create an instance of {@link ModifierMarkupRef }
     * 
     */
    public ModifierMarkupRef createModifierMarkupRef() {
        return new ModifierMarkupRef();
    }

    /**
     * Create an instance of {@link TaxonNameRef }
     * 
     */
    public TaxonNameRef createTaxonNameRef() {
        return new TaxonNameRef();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link DescriptionScopeSet }
     * 
     */
    public DescriptionScopeSet createDescriptionScopeSet() {
        return new DescriptionScopeSet();
    }

    /**
     * Create an instance of {@link SamplingEventSet }
     * 
     */
    public SamplingEventSet createSamplingEventSet() {
        return new SamplingEventSet();
    }

    /**
     * Create an instance of {@link PublicationRef }
     * 
     */
    public PublicationRef createPublicationRef() {
        return new PublicationRef();
    }

    /**
     * Create an instance of {@link ValueRange }
     * 
     */
    public ValueRange createValueRange() {
        return new ValueRange();
    }

    /**
     * Create an instance of {@link CharacterTreeSet }
     * 
     */
    public CharacterTreeSet createCharacterTreeSet() {
        return new CharacterTreeSet();
    }

    /**
     * Create an instance of {@link CharTreeDesignedForSet }
     * 
     */
    public CharTreeDesignedForSet createCharTreeDesignedForSet() {
        return new CharTreeDesignedForSet();
    }

    /**
     * Create an instance of {@link ConceptStateRef }
     * 
     */
    public ConceptStateRef createConceptStateRef() {
        return new ConceptStateRef();
    }

    /**
     * Create an instance of {@link IPRStatementSet }
     * 
     */
    public IPRStatementSet createIPRStatementSet() {
        return new IPRStatementSet();
    }

    /**
     * Create an instance of {@link LinneanCanonicalTaxonAuthorship }
     * 
     */
    public LinneanCanonicalTaxonAuthorship createLinneanCanonicalTaxonAuthorship() {
        return new LinneanCanonicalTaxonAuthorship();
    }

    /**
     * Create an instance of {@link StateMarkup }
     * 
     */
    public StateMarkup createStateMarkup() {
        return new StateMarkup();
    }

    /**
     * Create an instance of {@link ContributorRefSeq }
     * 
     */
    public ContributorRefSeq createContributorRefSeq() {
        return new ContributorRefSeq();
    }

    /**
     * Create an instance of {@link RichAgentRef }
     * 
     */
    public RichAgentRef createRichAgentRef() {
        return new RichAgentRef();
    }

    /**
     * Create an instance of {@link TaxonIdentification }
     * 
     */
    public TaxonIdentification createTaxonName() {
        return new TaxonIdentification();
    }

    /**
     * Create an instance of {@link UnivarStatMeasureElaboration }
     * 
     */
    public UnivarStatMeasureElaboration createUnivarStatMeasureElaboration() {
        return new UnivarStatMeasureElaboration();
    }

    /**
     * Create an instance of {@link StoredKeyLeadSeq.Lead }
     * 
     */
    public StoredKeyLeadSeq.Lead createStoredKeyLeadSeqLead() {
        return new StoredKeyLeadSeq.Lead();
    }

    /**
     * Create an instance of {@link AbstractShortStringPlusRef }
     * 
     */
    public AbstractShortStringPlusRef createAbstractShortStringPlusRef() {
        return new AbstractShortStringPlusRef();
    }

    /**
     * Create an instance of {@link QuantSampleData }
     * 
     */
    public QuantSampleData createQuantSampleData() {
        return new QuantSampleData();
    }

    /**
     * Create an instance of {@link AudienceCore }
     * 
     */
    public AudienceCore createAudienceCore() {
        return new AudienceCore();
    }

    /**
     * Create an instance of {@link CharacterTree }
     * 
     */
    public CharacterTree createCharacterTree() {
        return new CharacterTree();
    }

    /**
     * Create an instance of {@link CharacterStateSeq }
     * 
     */
    public CharacterStateSeq createCharacterStateSeq() {
        return new CharacterStateSeq();
    }

    /**
     * Create an instance of {@link StoredKeyNode }
     * 
     */
    public StoredKeyNode createStoredKeyNode() {
        return new StoredKeyNode();
    }

    /**
     * Create an instance of {@link TaxonHierarchySet }
     * 
     */
    public TaxonHierarchySet createTaxonHierarchySet() {
        return new TaxonHierarchySet();
    }

    /**
     * Create an instance of {@link CharacterStateRef }
     * 
     */
    public CharacterStateRef createCharacterStateRef() {
        return new CharacterStateRef();
    }

    /**
     * Create an instance of {@link DetailText }
     * 
     */
    public DetailText createDetailText() {
        return new DetailText();
    }

    /**
     * Create an instance of {@link SamplingEvent }
     * 
     */
    public SamplingEvent createSamplingEvent() {
        return new SamplingEvent();
    }

    /**
     * Create an instance of {@link DescriptiveConceptRefSeq }
     * 
     */
    public DescriptiveConceptRefSeq createDescriptiveConceptRefSeq() {
        return new DescriptiveConceptRefSeq();
    }

    /**
     * Create an instance of {@link VersionExtension }
     * 
     */
    public VersionExtension createVersionExtension() {
        return new VersionExtension();
    }

    /**
     * Create an instance of {@link CategoricalCharMappingSet }
     * 
     */
    public CategoricalCharMappingSet createCategoricalCharMappingSet() {
        return new CategoricalCharMappingSet();
    }

    /**
     * Create an instance of {@link CodedDescriptionSet }
     * 
     */
    public CodedDescriptionSet createCodedDescriptionSet() {
        return new CodedDescriptionSet();
    }

    /**
     * Create an instance of {@link NaturalLanguagePhraseSet }
     * 
     */
    public NaturalLanguagePhraseSet createNaturalLanguagePhraseSet() {
        return new NaturalLanguagePhraseSet();
    }

    /**
     * Create an instance of {@link UnivarParamStatMeasure }
     * 
     */
    public UnivarParamStatMeasure createUnivarParamStatMeasure() {
        return new UnivarParamStatMeasure();
    }

    /**
     * Create an instance of {@link UnivarSimpleStatMeasure }
     * 
     */
    public UnivarSimpleStatMeasure createUnivarSimpleStatMeasure() {
        return new UnivarSimpleStatMeasure();
    }

    /**
     * Create an instance of {@link PublicationSet }
     * 
     */
    public PublicationSet createPublicationSet() {
        return new PublicationSet();
    }

    /**
     * Create an instance of {@link MediaObjectRichRef }
     * 
     */
    public MediaObjectRichRef createMediaObjectRichRef() {
        return new MediaObjectRichRef();
    }

    /**
     * Create an instance of {@link UnivarParamStatMeasureData }
     * 
     */
    public UnivarParamStatMeasureData createUnivarParamStatMeasureData() {
        return new UnivarParamStatMeasureData();
    }

    /**
     * Create an instance of {@link ModifierSeq }
     * 
     */
    public ModifierSeq createModifierSeq() {
        return new ModifierSeq();
    }

    /**
     * Create an instance of {@link DescriptiveConceptRef }
     * 
     */
    public DescriptiveConceptRef createDescriptiveConceptRef() {
        return new DescriptiveConceptRef();
    }

    /**
     * Create an instance of {@link TaxonHierarchy }
     * 
     */
    public TaxonHierarchy createTaxonHierarchy() {
        return new TaxonHierarchy();
    }

    /**
     * Create an instance of {@link ValueRangeOrVerbatim }
     * 
     */
    public ValueRangeOrVerbatim createValueRangeOrVerbatim() {
        return new ValueRangeOrVerbatim();
    }

    /**
     * Create an instance of {@link QuantSummaryData }
     * 
     */
    public QuantSummaryData createQuantSummaryData() {
        return new QuantSummaryData();
    }

    /**
     * Create an instance of {@link Specimen }
     * 
     */
    public Specimen createSpecimen() {
        return new Specimen();
    }

    /**
     * Create an instance of {@link ZeroToOneEstimateRange }
     * 
     */
    public ZeroToOneEstimateRange createZeroToOneEstimateRange() {
        return new ZeroToOneEstimateRange();
    }

    /**
     * Create an instance of {@link ModifierRefWithData }
     * 
     */
    public ModifierRefWithData createModifierRefWithData() {
        return new ModifierRefWithData();
    }

    /**
     * Create an instance of {@link NaturalLanguageDescription }
     * 
     */
    public NaturalLanguageDescription createNaturalLanguageDescription() {
        return new NaturalLanguageDescription();
    }

    /**
     * Create an instance of {@link UnivarAnyStatMeasure }
     * 
     */
    public UnivarAnyStatMeasure createUnivarAnyStatMeasure() {
        return new UnivarAnyStatMeasure();
    }

    /**
     * Create an instance of {@link MediaObjectRef }
     * 
     */
    public MediaObjectRef createMediaObjectRef() {
        return new MediaObjectRef();
    }

    /**
     * Create an instance of {@link TaxonomicRank }
     * 
     */
    public TaxonomicRank createTaxonomicRank() {
        return new TaxonomicRank();
    }

    /**
     * Create an instance of {@link DescriptiveConceptSet }
     * 
     */
    public DescriptiveConceptSet createDescriptiveConceptSet() {
        return new DescriptiveConceptSet();
    }

    /**
     * Create an instance of {@link Sex }
     * 
     */
    public Sex createSex() {
        return new Sex();
    }

    /**
     * Create an instance of {@link RevisionStatus }
     * 
     */
    public RevisionStatus createRevisionStatus() {
        return new RevisionStatus();
    }

    /**
     * Create an instance of {@link RecommendedMeasureSeq }
     * 
     */
    public RecommendedMeasureSeq createRecommendedMeasureSeq() {
        return new RecommendedMeasureSeq();
    }

    /**
     * Create an instance of {@link SpecimenRef }
     * 
     */
    public SpecimenRef createSpecimenRef() {
        return new SpecimenRef();
    }

    /**
     * Create an instance of {@link FreeFormTextData }
     * 
     */
    public FreeFormTextData createFreeFormTextData() {
        return new FreeFormTextData();
    }

    /**
     * Create an instance of {@link QuantitativeCharMappingSet }
     * 
     */
    public QuantitativeCharMappingSet createQuantitativeCharMappingSet() {
        return new QuantitativeCharMappingSet();
    }

    /**
     * Create an instance of {@link CatSummaryData }
     * 
     */
    public CatSummaryData createCatSummaryData() {
        return new CatSummaryData();
    }

    /**
     * Create an instance of {@link TaxonHierarchyNodeSeq }
     * 
     */
    public TaxonHierarchyNodeSeq createTaxonHierarchyNodeSeq() {
        return new TaxonHierarchyNodeSeq();
    }

    /**
     * Create an instance of {@link MediaObjectCore }
     * 
     */
    public MediaObjectCore createMediaObjectCore() {
        return new MediaObjectCore();
    }

    /**
     * Create an instance of {@link EncodedContent }
     * 
     */
    public EncodedContent createEncodedContent() {
        return new EncodedContent();
    }

    /**
     * Create an instance of {@link CharacterLocalStateDef }
     * 
     */
    public CharacterLocalStateDef createCharacterLocalStateDef() {
        return new CharacterLocalStateDef();
    }

    /**
     * Create an instance of {@link StoredKeyNode.Reticulation }
     * 
     */
    public StoredKeyNode.Reticulation createStoredKeyNodeReticulation() {
        return new StoredKeyNode.Reticulation();
    }

    /**
     * Create an instance of {@link ValueMarkup }
     * 
     */
    public ValueMarkup createValueMarkup() {
        return new ValueMarkup();
    }

    /**
     * Create an instance of {@link QuantitativeCharDefaults }
     * 
     */
    public QuantitativeCharDefaults createQuantitativeCharDefaults() {
        return new QuantitativeCharDefaults();
    }

    /**
     * Create an instance of {@link LinneanCanonicalTaxonName }
     * 
     */
    public LinneanCanonicalTaxonName createLinneanCanonicalTaxonName() {
        return new LinneanCanonicalTaxonName();
    }

    /**
     * Create an instance of {@link SpecimenSet }
     * 
     */
    public SpecimenSet createSpecimenSet() {
        return new SpecimenSet();
    }

    /**
     * Create an instance of {@link Rating }
     * 
     */
    public Rating createRating() {
        return new Rating();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = QuantitativeMarkup.class)
    public JAXBElement<MarkupText> createQuantitativeMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStatusMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Status", scope = QuantitativeMarkup.class)
    public JAXBElement<DataStatusMarkup> createQuantitativeMarkupStatus(DataStatusMarkup value) {
        return new JAXBElement<DataStatusMarkup>(_QuantitativeMarkupStatus_QNAME, DataStatusMarkup.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Value", scope = QuantitativeMarkup.class)
    public JAXBElement<ValueMarkup> createQuantitativeMarkupValue(ValueMarkup value) {
        return new JAXBElement<ValueMarkup>(_QuantitativeMarkupValue_QNAME, ValueMarkup.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasureMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Measure", scope = QuantitativeMarkup.class)
    public JAXBElement<MeasureMarkup> createQuantitativeMarkupMeasure(MeasureMarkup value) {
        return new JAXBElement<MeasureMarkup>(_QuantitativeMarkupMeasure_QNAME, MeasureMarkup.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PMeasureMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "PMeasure", scope = QuantitativeMarkup.class)
    public JAXBElement<PMeasureMarkup> createQuantitativeMarkupPMeasure(PMeasureMarkup value) {
        return new JAXBElement<PMeasureMarkup>(_QuantitativeMarkupPMeasure_QNAME, PMeasureMarkup.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = QuantitativeMarkup.class)
    public JAXBElement<MarkupText> createQuantitativeMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierMarkupRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Modifier", scope = QuantitativeMarkup.class)
    public JAXBElement<ModifierMarkupRef> createQuantitativeMarkupModifier(ModifierMarkupRef value) {
        return new JAXBElement<ModifierMarkupRef>(_QuantitativeMarkupModifier_QNAME, ModifierMarkupRef.class, QuantitativeMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = FreeFormTextMarkup.class)
    public JAXBElement<MarkupText> createFreeFormTextMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, FreeFormTextMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStatusMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Status", scope = FreeFormTextMarkup.class)
    public JAXBElement<DataStatusMarkup> createFreeFormTextMarkupStatus(DataStatusMarkup value) {
        return new JAXBElement<DataStatusMarkup>(_QuantitativeMarkupStatus_QNAME, DataStatusMarkup.class, FreeFormTextMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = FreeFormTextMarkup.class)
    public JAXBElement<MarkupText> createFreeFormTextMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, FreeFormTextMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = StateMarkup.class)
    public JAXBElement<MarkupText> createStateMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, StateMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierMarkupRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Modifier", scope = StateMarkup.class)
    public JAXBElement<ModifierMarkupRef> createStateMarkupModifier(ModifierMarkupRef value) {
        return new JAXBElement<ModifierMarkupRef>(_QuantitativeMarkupModifier_QNAME, ModifierMarkupRef.class, StateMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = StateMarkup.class)
    public JAXBElement<MarkupText> createStateMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, StateMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "State", scope = CategoricalMarkup.class)
    public JAXBElement<StateMarkup> createCategoricalMarkupState(StateMarkup value) {
        return new JAXBElement<StateMarkup>(_CategoricalMarkupState_QNAME, StateMarkup.class, CategoricalMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = CategoricalMarkup.class)
    public JAXBElement<MarkupText> createCategoricalMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, CategoricalMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataStatusMarkup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Status", scope = CategoricalMarkup.class)
    public JAXBElement<DataStatusMarkup> createCategoricalMarkupStatus(DataStatusMarkup value) {
        return new JAXBElement<DataStatusMarkup>(_QuantitativeMarkupStatus_QNAME, DataStatusMarkup.class, CategoricalMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifierMarkupRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Modifier", scope = CategoricalMarkup.class)
    public JAXBElement<ModifierMarkupRef> createCategoricalMarkupModifier(ModifierMarkupRef value) {
        return new JAXBElement<ModifierMarkupRef>(_QuantitativeMarkupModifier_QNAME, ModifierMarkupRef.class, CategoricalMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = CategoricalMarkup.class)
    public JAXBElement<MarkupText> createCategoricalMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, CategoricalMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "TextChar", scope = SamplingUnitDataSet.class)
    public JAXBElement<FreeFormTextData> createSamplingUnitDataSetTextChar(FreeFormTextData value) {
        return new JAXBElement<FreeFormTextData>(_SamplingUnitDataSetTextChar_QNAME, FreeFormTextData.class, SamplingUnitDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantSampleData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Quantitative", scope = SamplingUnitDataSet.class)
    public JAXBElement<QuantSampleData> createSamplingUnitDataSetQuantitative(QuantSampleData value) {
        return new JAXBElement<QuantSampleData>(_SamplingUnitDataSetQuantitative_QNAME, QuantSampleData.class, SamplingUnitDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = SamplingUnitDataSet.class)
    public JAXBElement<FreeFormTextData> createSamplingUnitDataSetText(FreeFormTextData value) {
        return new JAXBElement<FreeFormTextData>(_QuantitativeMarkupText_QNAME, FreeFormTextData.class, SamplingUnitDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MolecularSequenceData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Sequence", scope = SamplingUnitDataSet.class)
    public JAXBElement<MolecularSequenceData> createSamplingUnitDataSetSequence(MolecularSequenceData value) {
        return new JAXBElement<MolecularSequenceData>(_SamplingUnitDataSetSequence_QNAME, MolecularSequenceData.class, SamplingUnitDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatSampleData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Categorical", scope = SamplingUnitDataSet.class)
    public JAXBElement<CatSampleData> createSamplingUnitDataSetCategorical(CatSampleData value) {
        return new JAXBElement<CatSampleData>(_SamplingUnitDataSetCategorical_QNAME, CatSampleData.class, SamplingUnitDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = DataStatusMarkup.class)
    public JAXBElement<MarkupText> createDataStatusMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, DataStatusMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = DataStatusMarkup.class)
    public JAXBElement<MarkupText> createDataStatusMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, DataStatusMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "TextChar", scope = SummaryDataSet.class)
    public JAXBElement<FreeFormTextData> createSummaryDataSetTextChar(FreeFormTextData value) {
        return new JAXBElement<FreeFormTextData>(_SamplingUnitDataSetTextChar_QNAME, FreeFormTextData.class, SummaryDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QuantSummaryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Quantitative", scope = SummaryDataSet.class)
    public JAXBElement<QuantSummaryData> createSummaryDataSetQuantitative(QuantSummaryData value) {
        return new JAXBElement<QuantSummaryData>(_SamplingUnitDataSetQuantitative_QNAME, QuantSummaryData.class, SummaryDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = SummaryDataSet.class)
    public JAXBElement<FreeFormTextData> createSummaryDataSetText(FreeFormTextData value) {
        return new JAXBElement<FreeFormTextData>(_QuantitativeMarkupText_QNAME, FreeFormTextData.class, SummaryDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MolecularSequenceData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Sequence", scope = SummaryDataSet.class)
    public JAXBElement<MolecularSequenceData> createSummaryDataSetSequence(MolecularSequenceData value) {
        return new JAXBElement<MolecularSequenceData>(_SamplingUnitDataSetSequence_QNAME, MolecularSequenceData.class, SummaryDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CatSummaryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Categorical", scope = SummaryDataSet.class)
    public JAXBElement<CatSummaryData> createSummaryDataSetCategorical(CatSummaryData value) {
        return new JAXBElement<CatSummaryData>(_SamplingUnitDataSetCategorical_QNAME, CatSummaryData.class, SummaryDataSet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Text", scope = ValueMarkup.class)
    public JAXBElement<MarkupText> createValueMarkupText(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupText_QNAME, MarkupText.class, ValueMarkup.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MarkupText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rs.tdwg.org/UBIF/2006/", name = "Note", scope = ValueMarkup.class)
    public JAXBElement<MarkupText> createValueMarkupNote(MarkupText value) {
        return new JAXBElement<MarkupText>(_QuantitativeMarkupNote_QNAME, MarkupText.class, ValueMarkup.class, value);
    }

}
