//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Adds OwnerAndIPR and RevisionData to AbstractObject
 * 
 * <p>Java class for OwnedAbstractObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OwnedAbstractObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}VersionedAbstractObject">
 *       &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}OwnerAndIPRStatements"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OwnedAbstractObject", propOrder = {
    "owners",
    "iprStatements"
})
@XmlSeeAlso({
    Dataset.class,
    MediaObject.class
})
public abstract class OwnedAbstractObject
    extends VersionedAbstractObject
{

    @XmlElement(name = "Owners")
    protected OwnerRefSeq owners;
    @XmlElement(name = "IPRStatements")
    protected IPRStatementSet iprStatements;

    /**
     * Gets the value of the owners property.
     * 
     * @return
     *     possible object is
     *     {@link OwnerRefSeq }
     *     
     */
    public OwnerRefSeq getOwners() {
        return owners;
    }

    /**
     * Sets the value of the owners property.
     * 
     * @param value
     *     allowed object is
     *     {@link OwnerRefSeq }
     *     
     */
    public void setOwners(OwnerRefSeq value) {
        this.owners = value;
    }

    /**
     * Gets the value of the iprStatements property.
     * 
     * @return
     *     possible object is
     *     {@link IPRStatementSet }
     *     
     */
    public IPRStatementSet getIPRStatements() {
        return iprStatements;
    }

    /**
     * Sets the value of the iprStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPRStatementSet }
     *     
     */
    public void setIPRStatements(IPRStatementSet value) {
        this.iprStatements = value;
    }

}
