//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * Inner class, used only within QuantitativeCharacter
 * 
 * <p>Java class for QuantitativeCharDefaults complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantitativeCharDefaults">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeasurementUnitPrefix" type="{http://rs.tdwg.org/UBIF/2006/}MeasurementUnitPrefixEnum" minOccurs="0"/>
 *         &lt;element name="SignificantFigures" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="DecimalPlaces" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantitativeCharDefaults", propOrder = {
    "measurementUnitPrefix",
    "significantFigures",
    "decimalPlaces",
    "nextVersion"
})
public class QuantitativeCharDefaults {

    @XmlElement(name = "MeasurementUnitPrefix", defaultValue = "noprefix")
    protected QName measurementUnitPrefix;
    @XmlElement(name = "SignificantFigures")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger significantFigures;
    @XmlElement(name = "DecimalPlaces", defaultValue = "4")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger decimalPlaces;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the measurementUnitPrefix property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getMeasurementUnitPrefix() {
        return measurementUnitPrefix;
    }

    /**
     * Sets the value of the measurementUnitPrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setMeasurementUnitPrefix(QName value) {
        this.measurementUnitPrefix = value;
    }

    /**
     * Gets the value of the significantFigures property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSignificantFigures() {
        return significantFigures;
    }

    /**
     * Sets the value of the significantFigures property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSignificantFigures(BigInteger value) {
        this.significantFigures = value;
    }

    /**
     * Gets the value of the decimalPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDecimalPlaces() {
        return decimalPlaces;
    }

    /**
     * Sets the value of the decimalPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDecimalPlaces(BigInteger value) {
        this.decimalPlaces = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
