//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * # Extends the abstract CharacterMarkup for use with numerical (statistical measures) data as well as a list of sample measurement values.
 * 
 * <p>Java class for QuantitativeMarkup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantitativeMarkup">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractCharacterMarkup">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Status" type="{http://rs.tdwg.org/UBIF/2006/}DataStatusMarkup"/>
 *         &lt;element name="Modifier" type="{http://rs.tdwg.org/UBIF/2006/}ModifierMarkupRef"/>
 *         &lt;element name="Measure" type="{http://rs.tdwg.org/UBIF/2006/}MeasureMarkup"/>
 *         &lt;element name="PMeasure" type="{http://rs.tdwg.org/UBIF/2006/}PMeasureMarkup"/>
 *         &lt;element name="Value" type="{http://rs.tdwg.org/UBIF/2006/}ValueMarkup"/>
 *         &lt;element name="Note" type="{http://rs.tdwg.org/UBIF/2006/}MarkupText"/>
 *         &lt;element name="Text" type="{http://rs.tdwg.org/UBIF/2006/}MarkupText"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantitativeMarkup", propOrder = {
    "statusOrModifierOrMeasure"
})
public class QuantitativeMarkup
    extends AbstractCharacterMarkup
{

    @XmlElementRefs({
        @XmlElementRef(name = "Measure", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Note", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Value", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Modifier", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "PMeasure", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Status", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> statusOrModifierOrMeasure;

    /**
     * Gets the value of the statusOrModifierOrMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statusOrModifierOrMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatusOrModifierOrMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link MeasureMarkup }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkupText }{@code >}
     * {@link JAXBElement }{@code <}{@link MarkupText }{@code >}
     * {@link JAXBElement }{@code <}{@link ModifierMarkupRef }{@code >}
     * {@link JAXBElement }{@code <}{@link ValueMarkup }{@code >}
     * {@link JAXBElement }{@code <}{@link PMeasureMarkup }{@code >}
     * {@link JAXBElement }{@code <}{@link DataStatusMarkup }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getStatusOrModifierOrMeasure() {
        if (statusOrModifierOrMeasure == null) {
            statusOrModifierOrMeasure = new ArrayList<JAXBElement<?>>();
        }
        return this.statusOrModifierOrMeasure;
    }

}
