//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * Inner class, used only within QuantitativeCharacter
 * 
 * <p>Java class for QuantitativeCharAssumptions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QuantitativeCharAssumptions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MeasurementScale" type="{http://rs.tdwg.org/UBIF/2006/}QuantitativeMeasurementScaleEnum" minOccurs="0"/>
 *         &lt;element name="ValuesAreInteger" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Continuous" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PlausibleRange" type="{http://rs.tdwg.org/UBIF/2006/}ValueRange" minOccurs="0"/>
 *         &lt;element name="CircularDataRange" type="{http://rs.tdwg.org/UBIF/2006/}ValueRange" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QuantitativeCharAssumptions", propOrder = {
    "measurementScale",
    "valuesAreInteger",
    "continuous",
    "plausibleRange",
    "circularDataRange",
    "nextVersion"
})
public class QuantitativeCharAssumptions {

    @XmlElement(name = "MeasurementScale")
    protected QName measurementScale;
    @XmlElement(name = "ValuesAreInteger")
    protected Boolean valuesAreInteger;
    @XmlElement(name = "Continuous")
    protected Boolean continuous;
    @XmlElement(name = "PlausibleRange")
    protected ValueRange plausibleRange;
    @XmlElement(name = "CircularDataRange")
    protected ValueRange circularDataRange;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the measurementScale property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getMeasurementScale() {
        return measurementScale;
    }

    /**
     * Sets the value of the measurementScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setMeasurementScale(QName value) {
        this.measurementScale = value;
    }

    /**
     * Gets the value of the valuesAreInteger property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isValuesAreInteger() {
        return valuesAreInteger;
    }

    /**
     * Sets the value of the valuesAreInteger property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setValuesAreInteger(Boolean value) {
        this.valuesAreInteger = value;
    }

    /**
     * Gets the value of the continuous property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContinuous() {
        return continuous;
    }

    /**
     * Sets the value of the continuous property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContinuous(Boolean value) {
        this.continuous = value;
    }

    /**
     * Gets the value of the plausibleRange property.
     * 
     * @return
     *     possible object is
     *     {@link ValueRange }
     *     
     */
    public ValueRange getPlausibleRange() {
        return plausibleRange;
    }

    /**
     * Sets the value of the plausibleRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueRange }
     *     
     */
    public void setPlausibleRange(ValueRange value) {
        this.plausibleRange = value;
    }

    /**
     * Gets the value of the circularDataRange property.
     * 
     * @return
     *     possible object is
     *     {@link ValueRange }
     *     
     */
    public ValueRange getCircularDataRange() {
        return circularDataRange;
    }

    /**
     * Sets the value of the circularDataRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueRange }
     *     
     */
    public void setCircularDataRange(ValueRange value) {
        this.circularDataRange = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
