//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A container for a sample data, with repeated sampling units, each of which may record multiple characters that are observed together.
 * 
 * <p>Java class for SamplingEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SamplingEvent">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractEvent">
 *       &lt;sequence>
 *         &lt;element name="SamplingUnit" type="{http://rs.tdwg.org/UBIF/2006/}SamplingUnitDataSet" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="randomized" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SamplingEvent", propOrder = {
    "samplingUnit"
})
public class SamplingEvent
    extends AbstractEvent
{

    @XmlElement(name = "SamplingUnit", required = true)
    protected List<SamplingUnitDataSet> samplingUnit;
    @XmlAttribute(name = "randomized")
    protected Boolean randomized;

    /**
     * Gets the value of the samplingUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the samplingUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSamplingUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SamplingUnitDataSet }
     * 
     * 
     */
    public List<SamplingUnitDataSet> getSamplingUnit() {
        if (samplingUnit == null) {
            samplingUnit = new ArrayList<SamplingUnitDataSet>();
        }
        return this.samplingUnit;
    }

    /**
     * Gets the value of the randomized property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isRandomized() {
        if (randomized == null) {
            return false;
        } else {
            return randomized;
        }
    }

    /**
     * Sets the value of the randomized property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRandomized(Boolean value) {
        this.randomized = value;
    }

}
