//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Like Representation, but without Detail, and without Label role (may be treated as if Label role were fixed to 'full').
 * 
 * <p>Java class for SimpleRepresentation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimpleRepresentation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}Alt">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Label" type="{http://rs.tdwg.org/UBIF/2006/}ShortStringL"/>
 *         &lt;element name="MediaObject" type="{http://rs.tdwg.org/UBIF/2006/}MediaObjectRichRef"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimpleRepresentation", propOrder = {
    "labelOrMediaObject"
})
public class SimpleRepresentation
    extends Alt
{

    @XmlElements({
        @XmlElement(name = "Label", type = ShortStringL.class),
        @XmlElement(name = "MediaObject", type = MediaObjectRichRef.class)
    })
    protected List<Object> labelOrMediaObject;

    /**
     * Gets the value of the labelOrMediaObject property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrMediaObject property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrMediaObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShortStringL }
     * {@link MediaObjectRichRef }
     * 
     * 
     */
    public List<Object> getLabelOrMediaObject() {
        if (labelOrMediaObject == null) {
            labelOrMediaObject = new ArrayList<Object>();
        }
        return this.labelOrMediaObject;
    }

}
