//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * A collection of character summary data elements (all of which are derived from CharSummaryData abstractType
 * 
 * <p>Java class for SummaryDataSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SummaryDataSet">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}Set">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Categorical" type="{http://rs.tdwg.org/UBIF/2006/}CatSummaryData"/>
 *         &lt;element name="Quantitative" type="{http://rs.tdwg.org/UBIF/2006/}QuantSummaryData"/>
 *         &lt;element name="Sequence" type="{http://rs.tdwg.org/UBIF/2006/}MolecularSequenceData"/>
 *         &lt;element name="TextChar" type="{http://rs.tdwg.org/UBIF/2006/}FreeFormTextData"/>
 *         &lt;element name="Text" type="{http://rs.tdwg.org/UBIF/2006/}FreeFormTextData"/>
 *       &lt;/choice>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SummaryDataSet", propOrder = {
    "categoricalOrQuantitativeOrSequence"
})
public class SummaryDataSet
    extends Set
{

    @XmlElementRefs({
        @XmlElementRef(name = "Categorical", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Quantitative", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "TextChar", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Sequence", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "Text", namespace = "http://rs.tdwg.org/UBIF/2006/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends AbstractCharSummaryData>> categoricalOrQuantitativeOrSequence;

    /**
     * Gets the value of the categoricalOrQuantitativeOrSequence property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoricalOrQuantitativeOrSequence property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoricalOrQuantitativeOrSequence().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link CatSummaryData }{@code >}
     * {@link JAXBElement }{@code <}{@link QuantSummaryData }{@code >}
     * {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}
     * {@link JAXBElement }{@code <}{@link FreeFormTextData }{@code >}
     * {@link JAXBElement }{@code <}{@link MolecularSequenceData }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends AbstractCharSummaryData>> getCategoricalOrQuantitativeOrSequence() {
        if (categoricalOrQuantitativeOrSequence == null) {
            categoricalOrQuantitativeOrSequence = new ArrayList<JAXBElement<? extends AbstractCharSummaryData>>();
        }
        return this.categoricalOrQuantitativeOrSequence;
    }

}
