//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  A kind of local extension of the base definition of a statistical measure; used inside in concepts, adding, e. g., formatting information.
 * 
 * <p>Java class for UnivarStatMeasureElaboration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UnivarStatMeasureElaboration">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractVocabularyBase">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="Measure" type="{http://rs.tdwg.org/UBIF/2006/}UnivarSimpleStatMeasure"/>
 *           &lt;sequence>
 *             &lt;element name="PMeasure" type="{http://rs.tdwg.org/UBIF/2006/}UnivarParamStatMeasure"/>
 *             &lt;element name="Parameter" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *           &lt;/sequence>
 *         &lt;/choice>
 *         &lt;element name="FormatPattern" type="{http://rs.tdwg.org/UBIF/2006/}NumericFormatPattern" minOccurs="0"/>
 *         &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}SpecificExtension" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnivarStatMeasureElaboration", propOrder = {
    "measure",
    "pMeasure",
    "parameter",
    "formatPattern",
    "nextVersion"
})
public class UnivarStatMeasureElaboration
    extends AbstractVocabularyBase
{

    @XmlElement(name = "Measure")
    protected UnivarSimpleStatMeasure measure;
    @XmlElement(name = "PMeasure")
    protected UnivarParamStatMeasure pMeasure;
    @XmlElement(name = "Parameter")
    protected Double parameter;
    @XmlElement(name = "FormatPattern")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String formatPattern;
    @XmlElement(name = "NextVersion")
    protected VersionExtension nextVersion;

    /**
     * Gets the value of the measure property.
     * 
     * @return
     *     possible object is
     *     {@link UnivarSimpleStatMeasure }
     *     
     */
    public UnivarSimpleStatMeasure getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnivarSimpleStatMeasure }
     *     
     */
    public void setMeasure(UnivarSimpleStatMeasure value) {
        this.measure = value;
    }

    /**
     * Gets the value of the pMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link UnivarParamStatMeasure }
     *     
     */
    public UnivarParamStatMeasure getPMeasure() {
        return pMeasure;
    }

    /**
     * Sets the value of the pMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnivarParamStatMeasure }
     *     
     */
    public void setPMeasure(UnivarParamStatMeasure value) {
        this.pMeasure = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getParameter() {
        return parameter;
    }

    /**
     * Sets the value of the parameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setParameter(Double value) {
        this.parameter = value;
    }

    /**
     * Gets the value of the formatPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatPattern() {
        return formatPattern;
    }

    /**
     * Sets the value of the formatPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatPattern(String value) {
        this.formatPattern = value;
    }

    /**
     * Gets the value of the nextVersion property.
     * 
     * @return
     *     possible object is
     *     {@link VersionExtension }
     *     
     */
    public VersionExtension getNextVersion() {
        return nextVersion;
    }

    /**
     * Sets the value of the nextVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionExtension }
     *     
     */
    public void setNextVersion(VersionExtension value) {
        this.nextVersion = value;
    }

}
