//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * A value range as upper/lower value, optional, plus additional/alternative verbatim text.
 * 
 * <p>Java class for ValueRangeOrVerbatim complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValueRangeOrVerbatim">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="lower" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="upper" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="verbatim" type="{http://rs.tdwg.org/UBIF/2006/}ShortString" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValueRangeOrVerbatim")
@XmlSeeAlso({
    ZeroToOneRange.class,
    ValueRange.class
})
public class ValueRangeOrVerbatim {

    @XmlAttribute(name = "lower")
    protected Double lower;
    @XmlAttribute(name = "upper")
    protected Double upper;
    @XmlAttribute(name = "verbatim")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String verbatim;

    /**
     * Gets the value of the lower property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLower() {
        return lower;
    }

    /**
     * Sets the value of the lower property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLower(Double value) {
        this.lower = value;
    }

    /**
     * Gets the value of the upper property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getUpper() {
        return upper;
    }

    /**
     * Sets the value of the upper property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setUpper(Double value) {
        this.upper = value;
    }

    /**
     * Gets the value of the verbatim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerbatim() {
        return verbatim;
    }

    /**
     * Sets the value of the verbatim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerbatim(String value) {
        this.verbatim = value;
    }

}
