//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.18 at 10:21:36 AM MST 
//


package org.tdwg.rs.ubif._2006;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Adds RevisionData to AbstractObject
 * 
 * <p>Java class for VersionedAbstractObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VersionedAbstractObject">
 *   &lt;complexContent>
 *     &lt;extension base="{http://rs.tdwg.org/UBIF/2006/}AbstractObject">
 *       &lt;group ref="{http://rs.tdwg.org/UBIF/2006/}RevisionData"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VersionedAbstractObject", propOrder = {
    "revisionData"
})
@XmlSeeAlso({
    DescriptiveConcept.class,
    Agent.class,
    OwnedAbstractObject.class,
    CharacterTree.class,
    AbstractDescription.class,
    GeographicArea.class,
    TaxonHierarchy.class,
    Publication.class,
    Audience.class,
    StoredKey.class,
    TaxonName.class,
    Specimen.class,
    AbstractCharacterDefinition.class
})
public abstract class VersionedAbstractObject
    extends AbstractObject
{

    @XmlElement(name = "RevisionData")
    protected RevisionData revisionData;

    /**
     * Gets the value of the revisionData property.
     * 
     * @return
     *     possible object is
     *     {@link RevisionData }
     *     
     */
    public RevisionData getRevisionData() {
        return revisionData;
    }

    /**
     * Sets the value of the revisionData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RevisionData }
     *     
     */
    public void setRevisionData(RevisionData value) {
        this.revisionData = value;
    }

}
